---QUERY--

/*FIS GLOBAL SQL INTERVIEW QUESTIONS AND ANSWERS(WRITTEN)*/

---QUESTION--1
SELECT CHARINDEX('S','RAMSINGH')
--OUTPUT--4

---QUESTION--2
SELECT CASE WHEN NULL=NULL THEN 1 ELSE 0 END
--OUTPUT--0


---QUESTION--3
SELECT NULL UNION ALL SELECT N'NULL' UNION ALL SELECT NULL
--OUTPUT--


---QUESTION--4
SELECT SUBSTRING('123456789',CHARINDEX('XYZABC','Z'),4)
--OUTPUT--123

---QUESTION--5
SELECT LEFT('1234321',3)  AS LEFT3,RIGHT('1234321',3) AS RIGHT3
--OUTPUT--


---QUESTION--6
SELECT STUFF('FIS Global Pvt Ltd.',12,3,'INDIA')
--OUTPUT--FIS Global INDIA Ltd.


---QUESTION--7
SELECT REPLICATE('XYZ',3) 
--OUTPUT--XYZXYZXYZ


---QUESTION--8
SELECT REVERSE('1234321')
--OUTPUT--1234321


---QUESTION--9
SELECT REPLACE('ABCXYZ','ABC','XYZ')
--OUTPUT--XYZXYZ


---QUESTION--10
SELECT CHARINDEX('Ind','FIS Global INDIA Pvt Ltd. India',15)
#search IND,in this string,starting from this index
--OUTPUT--27


---QUESTION--11
SELECT PATINDEX('%Ind%','FIS Global INDIA Pvt Ltd. India')
--OUTPUT--12 return first index where ind found